worker_processes auto;

events {
    worker_connections 1024;
}

http {
    server_tokens off;

    # Rate limiting zones
    limit_req_zone $binary_remote_addr zone=web:10m rate=60r/m;
    limit_req_zone $binary_remote_addr zone=api:10m rate=30r/m;

    # HTTP — portal público (dev: sin redirect HTTPS, puerto local 443 ocupado por XAMPP)
    server {
        listen 80;
        server_name _;

        # Security headers
        add_header X-Frame-Options        "SAMEORIGIN"            always;
        add_header X-Content-Type-Options "nosniff"               always;
        add_header X-XSS-Protection       "1; mode=block"         always;
        add_header Referrer-Policy        "strict-origin-when-cross-origin" always;

        client_max_body_size 50M;

        # PHP portal
        location / {
            limit_req zone=web burst=30 nodelay;
            proxy_pass         http://php:80;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto $scheme;
            proxy_read_timeout 60s;
        }

    }

    # HTTPS — disponible en puerto 8443 (cert self-signed)
    server {
        listen 443 ssl;
        server_name _;

        ssl_certificate     /etc/nginx/ssl/fullchain.pem;
        ssl_certificate_key /etc/nginx/ssl/privkey.pem;
        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;
        ssl_session_cache   shared:SSL:10m;

        add_header X-Frame-Options        "SAMEORIGIN"            always;
        add_header X-Content-Type-Options "nosniff"               always;
        add_header Referrer-Policy        "strict-origin-when-cross-origin" always;

        client_max_body_size 50M;

        location / {
            limit_req zone=web burst=30 nodelay;
            proxy_pass         http://php:80;
            proxy_set_header   Host              $host;
            proxy_set_header   X-Real-IP         $remote_addr;
            proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Proto https;
            proxy_read_timeout 60s;
        }

    }
}
